# レディース
lady = Category.create(categoryName: "レディース")
lady_1 = lady.children.create(categoryName: "トップス")
lady_1.children.create([{categoryName: "Tシャツ/カットソー(半袖/袖なし)"},{categoryName: "Tシャツ/カットソー(七分/長袖)"},{categoryName: "シャツ/ブラウス(半袖/袖なし)"},{categoryName: "シャツ/ブラウス(七分/長袖)"},{categoryName: "ポロシャツ"},{categoryName: "キャミソール"},{categoryName: "タンクトップ"},{categoryName: "ホルターネック"},{categoryName: "ニット/セーター"},{categoryName: "チュニック"},{categoryName: "カーディガン/ボレロ"},{categoryName: "アンサンブル"},{categoryName: "ベスト/ジレ"},{categoryName: "パーカー"},{categoryName: "トレーナー/スウェット"},{categoryName: "ベアトップ/チューブトップ"},{categoryName: "ジャージ"},{categoryName: "その他"}])
lady_2 = lady.children.create(categoryName: "ジャケット/アウター")
lady_2.children.create([{categoryName: "テーラードジャケット"},{categoryName: "ノーカラージャケット"},{categoryName: "Gジャン/デニムジャケット"},{categoryName: "レザージャケット"},{categoryName: "ダウンジャケット"},{categoryName: "ライダースジャケット"},{categoryName: "ミリタリージャケット"},{categoryName: "ダウンベスト"},{categoryName: "ジャンパー/ブルゾン"},{categoryName: "ポンチョ"},{categoryName: "ロングコート"},{categoryName: "トレンチコート"},{categoryName: "ダッフルコート"},{categoryName: "ピーコート"},{categoryName: "チェスターコート"},{categoryName: "モッズコート"},{categoryName: "スタジャン"},{categoryName: "毛皮/ファーコート"},{categoryName: "スプリングコート"},{categoryName: "スカジャン"},{categoryName: "その他"}])
lady_3 = lady.children.create(categoryName: "パンツ")
lady_3.children.create([{categoryName: "デニム/ジーンズ"},{categoryName: "ショートパンツ"},{categoryName: "カジュアルパンツ"},{categoryName: "ハーフパンツ"},{categoryName: "チノパン"},{categoryName: "ワークパンツ/カーゴパンツ"},{categoryName: "クロップドパンツ"},{categoryName: "サロペット/オーバーオール"},{categoryName: "オールインワン"},{categoryName: "サルエルパンツ"},{categoryName: "ガウチョパンツ"},{categoryName: "その他"}])
lady_4 = lady.children.create(categoryName: "スカート")
lady_4.children.create([{categoryName: "ミニスカート"},{categoryName: "ひざ丈スカート"},{categoryName: "ロングスカート"},{categoryName: "キュロット"},{categoryName: "その他"}])
lady_5 = lady.children.create(categoryName: "ワンピース")
lady_5.children.create([{categoryName: "ミニワンピース"},{categoryName: "ひざ丈ワンピース"},{categoryName: "ロングワンピース"},{categoryName: "その他"}])
lady_6 = lady.children.create(categoryName: "靴")
lady_6.children.create([{categoryName: "ハイヒール/パンプス"},{categoryName: "ブーツ"},{categoryName: "サンダル"},{categoryName: "スニーカー"},{categoryName: "ミュール"},{categoryName: "モカシン"},{categoryName: "ローファー/革靴"},{categoryName: "フラットシューズ/バレエシューズ"},{categoryName: "長靴/レインシューズ"},{categoryName: "その他"}])
lady_7 = lady.children.create(categoryName: "ルームウェア/パジャマ")
lady_7.children.create([{categoryName: "パジャマ"},{categoryName: "ルームウェア"}])
lady_8 = lady.children.create(categoryName: "レッグウェア")
lady_8.children.create([{categoryName: "ソックス"},{categoryName: "スパッツ/レギンス"},{categoryName: "ストッキング/タイツ"},{categoryName: "レッグウォーマー"},{categoryName: "その他"}])
lady_9 = lady.children.create(categoryName: "帽子")
lady_9.children.create([{categoryName: "ニットキャップ/ビーニー"},{categoryName: "ハット"},{categoryName: "ハンチング/ベレー帽"},{categoryName: "キャップ"},{categoryName: "キャスケット"},{categoryName: "麦わら帽子"},{categoryName: "その他"}])
lady_10 = lady.children.create(categoryName: "バッグ")
lady_10.children.create([{categoryName: "ハンドバッグ"},{categoryName: "トートバッグ"},{categoryName: "エコバッグ"},{categoryName: "リュック/バックパック"},{categoryName: "ボストンバッグ"},{categoryName: "スポーツバッグ"},{categoryName: "ショルダーバッグ"},{categoryName: "クラッチバッグ"},{categoryName: "ポーチ/バニティ"},{categoryName: "ボディバッグ/ウェストバッグ"},{categoryName: "マザーズバッグ"},{categoryName: "メッセンジャーバッグ"},{categoryName: "ビジネスバッグ"},{categoryName: "旅行用バッグ/キャリーバッグ"},{categoryName: "ショップ袋"},{categoryName: "和装用バッグ"},{categoryName: "かごバッグ"},{categoryName: "その他"}])
lady_11 = lady.children.create(categoryName: "アクセサリー")
lady_11.children.create([{categoryName: "ネックレス"},{categoryName: "ブレスレット"},{categoryName: "バングル/リストバンド"},{categoryName: "リング"},{categoryName: "ピアス(片耳用)"},{categoryName: "ピアス(両耳用)"},{categoryName: "イヤリング"},{categoryName: "アンクレット"},{categoryName: "ブローチ/コサージュ"},{categoryName: "チャーム"},{categoryName: "その他"}])
lady_12 = lady.children.create(categoryName: "ヘアアクセサリー")
lady_12.children.create([{categoryName: "ヘアゴム/シュシュ"},{categoryName: "ヘアバンド/カチューシャ"},{categoryName: "ヘアピン"},{categoryName: "その他"}])
lady_13 = lady.children.create(categoryName: "小物")
lady_13.children.create([{categoryName: "長財布"},{categoryName: "折り財布"},{categoryName: "コインケース/小銭入れ"},{categoryName: "名刺入れ/定期入れ"},{categoryName: "キーケース"},{categoryName: "キーホルダー"},{categoryName: "手袋/アームカバー"},{categoryName: "ハンカチ"},{categoryName: "ベルト"},{categoryName: "マフラー/ショール"},{categoryName: "ストール/スヌード"},{categoryName: "バンダナ/スカーフ"},{categoryName: "ネックウォーマー"},{categoryName: "サスペンダー"},{categoryName: "サングラス/メガネ"},{categoryName: "モバイルケース/カバー"},{categoryName: "手帳"},{categoryName: "イヤマフラー"},{categoryName: "傘"},{categoryName: "レインコート/ポンチョ"},{categoryName: "ミラー"},{categoryName: "タバコグッズ"},{categoryName: "その他"}])
lady_14 = lady.children.create(categoryName: "時計")
lady_14.children.create([{categoryName: "腕時計(アナログ)"},{categoryName: "腕時計(デジタル)"},{categoryName: "ラバーベルト"},{categoryName: "レザーベルト"},{categoryName: "金属ベルト"},{categoryName: "その他"}])
lady_15 = lady.children.create(categoryName: "ウィッグ/エクステ")
lady_15.children.create([{categoryName: "前髪ウィッグ"},{categoryName: "ロングストレート"},{categoryName: "ロングカール"},{categoryName: "ショートストレート"},{categoryName: "ショートカール"},{categoryName: "その他"}])
lady_16 = lady.children.create(categoryName: "浴衣/水着")
lady_16.children.create([{categoryName: "浴衣"},{categoryName: "着物"},{categoryName: "振袖"},{categoryName: "長襦袢/半襦袢"},{categoryName: "水着セパレート"},{categoryName: "水着ワンピース"},{categoryName: "水着スポーツ用"},{categoryName: "その他"}])
lady_17 = lady.children.create(categoryName: "スーツ/フォーマル/ドレス")
lady_17.children.create([{categoryName: "スカートスーツ上下"},{categoryName: "パンツスーツ上下"},{categoryName: "ドレス"},{categoryName: "パーティーバッグ"},{categoryName: "シューズ"},{categoryName: "ウェディング"},{categoryName: "その他"}])
lady_18 = lady.children.create(categoryName: "マタニティ")
lady_18.children.create([{categoryName: "トップス"},{categoryName: "アウター"},{categoryName: "インナー"},{categoryName: "ワンピース"},{categoryName: "パンツ/スパッツ"},{categoryName: "スカート"},{categoryName: "パジャマ"},{categoryName: "授乳服"},{categoryName: "その他"}])
lady_19 = lady.children.create(categoryName: "その他")
lady_19.children.create([{categoryName: "コスプレ"},{categoryName: "下着"},{categoryName: "その他"}])

# メンズ
men = Category.create(categoryName: "メンズ")
men_1 = men.children.create(categoryName: "トップス")
men_1.children.create([{categoryName: "Tシャツ/カットソー(半袖/袖なし)"},{categoryName: "Tシャツ/カットソー(七分/長袖)"},{categoryName: "シャツ"},{categoryName: "ポロシャツ"},{categoryName: "タンクトップ"},{categoryName: "ニット/セーター"},{categoryName: "パーカー"},{categoryName: "カーディガン"},{categoryName: "スウェット"},{categoryName: "ジャージ"},{categoryName: "ベスト"},{categoryName: "その他"}])
men_2 = men.children.create(categoryName: "ジャケット/アウター")
men_2.children.create([{categoryName: "テーラードジャケット"},{categoryName: "ノーカラージャケット"},{categoryName: "Gジャン/デニムジャケット"},{categoryName: "レザージャケット"},{categoryName: "ダウンジャケット"},{categoryName: "ライダースジャケット"},{categoryName: "ミリタリージャケット"},{categoryName: "ナイロンジャケット"},{categoryName: "フライトジャケット"},{categoryName: "ダッフルコート"},{categoryName: "ピーコート"},{categoryName: "ステンカラーコート"},{categoryName: "トレンチコート"},{categoryName: "モッズコート"},{categoryName: "チェスターコート"},{categoryName: "スタジャン"},{categoryName: "スカジャン"},{categoryName: "ブルゾン"},{categoryName: "マウンテンパーカー"},{categoryName: "ダウンベスト"},{categoryName: "ポンチョ"},{categoryName: "カバーオール"},{categoryName: "その他"}])
men_3 = men.children.create(categoryName: "パンツ")
men_3.children.create([{categoryName: "デニム/ジーンズ"},{categoryName: "ワークパンツ/カーゴパンツ"},{categoryName: "スラックス"},{categoryName: "チノパン"},{categoryName: "ショートパンツ"},{categoryName: "ペインターパンツ"},{categoryName: "サルエルパンツ"},{categoryName: "オーバーオール"},{categoryName: "その他"}])
men_4 = men.children.create(categoryName: "靴")
men_4.children.create([{categoryName: "スニーカー"},{categoryName: "サンダル"},{categoryName: "ブーツ"},{categoryName: "モカシン"},{categoryName: "ドレス/ビジネス"},{categoryName: "長靴/レインシューズ"},{categoryName: "デッキシューズ"},{categoryName: "その他"}])
men_5 = men.children.create(categoryName: "バッグ")
men_5.children.create([{categoryName: "ショルダーバッグ"},{categoryName: "トートバッグ"},{categoryName: "ボストンバッグ"},{categoryName: "リュック/バックパック"},{categoryName: "ウエストポーチ"},{categoryName: "ボディーバッグ"},{categoryName: "ドラムバッグ"},{categoryName: "ビジネスバッグ"},{categoryName: "トラベルバッグ"},{categoryName: "メッセンジャーバッグ"},{categoryName: "エコバッグ"},{categoryName: "その他"}])
men_6 = men.children.create(categoryName: "スーツ")
men_6.children.create([{categoryName: "スーツジャケット"},{categoryName: "スーツベスト"},{categoryName: "スラックス"},{categoryName: "セットアップ"},{categoryName: "その他"}])
men_7 = men.children.create(categoryName: "帽子")
men_7.children.create([{categoryName: "キャップ"},{categoryName: "ハット"},{categoryName: "ニットキャップ/ビーニー"},{categoryName: "ハンチング/ベレー帽"},{categoryName: "キャスケット"},{categoryName: "サンバイザー"},{categoryName: "その他"}])
men_8 = men.children.create(categoryName: "アクセサリー")
men_8.children.create([{categoryName: "ネックレス"},{categoryName: "ブレスレット"},{categoryName: "バングル/リストバンド"},{categoryName: "リング"},{categoryName: "ピアス(片耳用)"},{categoryName: "ピアス(両耳用)"},{categoryName: "アンクレット"},{categoryName: "その他"}])
men_9 = men.children.create(categoryName: "小物")
men_9.children.create([{categoryName: "長財布"},{categoryName: "折り財布"},{categoryName: "マネークリップ"},{categoryName: "コインケース/小銭入れ"},{categoryName: "名刺入れ/定期入れ"},{categoryName: "キーケース"},{categoryName: "キーホルダー"},{categoryName: "ネクタイ"},{categoryName: "手袋"},{categoryName: "ハンカチ"},{categoryName: "ベルト"},{categoryName: "マフラー"},{categoryName: "ストール"},{categoryName: "バンダナ"},{categoryName: "ネックウォーマー"},{categoryName: "サスペンダー"},{categoryName: "ウォレットチェーン"},{categoryName: "サングラス/メガネ"},{categoryName: "モバイルケース/カバー"},{categoryName: "手帳"},{categoryName: "ストラップ"},{categoryName: "ネクタイピン"},{categoryName: "カフリンクス"},{categoryName: "イヤマフラー"},{categoryName: "傘"},{categoryName: "レインコート"},{categoryName: "ミラー"},{categoryName: "タバコグッズ"},{categoryName: "その他"}])
men_10 = men.children.create(categoryName: "時計")
men_10.children.create([{categoryName: "腕時計(アナログ)"},{categoryName: "腕時計(デジタル)"},{categoryName: "ラバーベルト"},{categoryName: "レザーベルト"},{categoryName: "金属ベルト"},{categoryName: "その他"}])
men_11 = men.children.create(categoryName: "水着")
men_11.children.create([{categoryName: "一般水着"},{categoryName: "スポーツ用"},{categoryName: "アクセサリー"},{categoryName: "その他"}])
men_12 = men.children.create(categoryName: "レッグウェア")
men_12.children.create([{categoryName: "ソックス"},{categoryName: "レギンス/スパッツ"},{categoryName: "レッグウォーマー"},{categoryName: "その他"}])
men_13 = men.children.create(categoryName: "アンダーウェア")
men_13.children.create([{categoryName: "トランクス"},{categoryName: "ボクサーパンツ"},{categoryName: "その他"}])
men_14 = men.children.create(categoryName: "その他")
men_14.children.create([{categoryName: "すべて"}])

# ベビー・キッズ
baby_kids = Category.create(categoryName: "ベビー・キッズ")
baby_kids_1 = baby_kids.children.create(categoryName: "ベビー服(女の子用) ~95cm")
baby_kids_1.children.create([{categoryName: "トップス"},{categoryName: "アウター"},{categoryName: "パンツ"},{categoryName: "スカート"},{categoryName: "ワンピース"},{categoryName: "ベビードレス"},{categoryName: "おくるみ"},{categoryName: "下着/肌着"},{categoryName: "パジャマ"},{categoryName: "ロンパース"},{categoryName: "その他"}])
baby_kids_2 = baby_kids.children.create(categoryName: "ベビー服(男の子用) ~95cm")
baby_kids_2.children.create([{categoryName: "トップス"},{categoryName: "アウター"},{categoryName: "パンツ"},{categoryName: "おくるみ"},{categoryName: "下着/肌着"},{categoryName: "パジャマ"},{categoryName: "ロンパース"},{categoryName: "その他"}])
baby_kids_3 = baby_kids.children.create(categoryName: "ベビー服(男女兼用) ~95cm")
baby_kids_3.children.create([{categoryName: "トップス"},{categoryName: "アウター"},{categoryName: "パンツ"},{categoryName: "おくるみ"},{categoryName: "下着/肌着"},{categoryName: "パジャマ"},{categoryName: "ロンパース"},{categoryName: "その他"}])
baby_kids_4 = baby_kids.children.create(categoryName: "キッズ服(女の子用) 100cm~")
baby_kids_4.children.create([{categoryName: "コート"},{categoryName: "ジャケット/上着"},{categoryName: "トップス(Tシャツ/カットソー)"},{categoryName: "トップス(トレーナー)"},{categoryName: "トップス(チュニック)"},{categoryName: "トップス(タンクトップ)"},{categoryName: "トップス(その他)"},{categoryName: "スカート"},{categoryName: "パンツ"},{categoryName: "ワンピース"},{categoryName: "セットアップ"},{categoryName: "パジャマ"},{categoryName: "フォーマル/ドレス"},{categoryName: "和服"},{categoryName: "浴衣"},{categoryName: "甚平"},{categoryName: "水着"},{categoryName: "その他"}])
baby_kids_5 = baby_kids.children.create(categoryName: "キッズ服(男の子用) 100cm~")
baby_kids_5.children.create([{categoryName: "コート"},{categoryName: "ジャケット/上着"},{categoryName: "トップス(Tシャツ/カットソー)"},{categoryName: "トップス(トレーナー)"},{categoryName: "トップス(その他)"},{categoryName: "パンツ"},{categoryName: "セットアップ"},{categoryName: "パジャマ"},{categoryName: "フォーマル/ドレス"},{categoryName: "和服"},{categoryName: "浴衣"},{categoryName: "甚平"},{categoryName: "水着"},{categoryName: "その他"}])
baby_kids_6 = baby_kids.children.create(categoryName: "キッズ服(男女兼用) 100cm~")
baby_kids_6.children.create([{categoryName: "コート"},{categoryName: "ジャケット/上着"},{categoryName: "トップス(Tシャツ/カットソー)"},{categoryName: "トップス(トレーナー)"},{categoryName: "トップス(その他)"},{categoryName: "ボトムス"},{categoryName: "パジャマ"},{categoryName: "その他"}])
baby_kids_7 = baby_kids.children.create(categoryName: "キッズ靴")
baby_kids_7.children.create([{categoryName: "スニーカー"},{categoryName: "サンダル"},{categoryName: "ブーツ"},{categoryName: "長靴"},{categoryName: "その他"}])
baby_kids_8 = baby_kids.children.create(categoryName: "子ども用ファッション小物")
baby_kids_8.children.create([{categoryName: "靴下/スパッツ"},{categoryName: "帽子"},{categoryName: "エプロン"},{categoryName: "サスペンダー"},{categoryName: "タイツ"},{categoryName: "ハンカチ"},{categoryName: "バンダナ"},{categoryName: "ベルト"},{categoryName: "マフラー"},{categoryName: "傘"},{categoryName: "手袋"},{categoryName: "スタイ"},{categoryName: "バッグ"},{categoryName: "その他"}])
baby_kids_9 = baby_kids.children.create(categoryName: "おむつ/トイレ/バス")
baby_kids_9.children.create([{categoryName: "おむつ用品"},{categoryName: "おまる/補助便座"},{categoryName: "トレーニングパンツ"},{categoryName: "ベビーバス"},{categoryName: "お風呂用品"},{categoryName: "その他"}])
baby_kids_10 = baby_kids.children.create(categoryName: "外出/移動用品")
baby_kids_10.children.create([{categoryName: "ベビーカー"},{categoryName: "抱っこひも/スリング"},{categoryName: "チャイルドシート"},{categoryName: "その他"}])
baby_kids_11 = baby_kids.children.create(categoryName: "授乳/食事")
baby_kids_11.children.create([{categoryName: "ミルク"},{categoryName: "ベビーフード"},{categoryName: "ベビー用食器"},{categoryName: "その他"}])
baby_kids_12 = baby_kids.children.create(categoryName: "ベビー家具/寝具/室内用品")
baby_kids_12.children.create([{categoryName: "ベッド"},{categoryName: "布団/毛布"},{categoryName: "イス"},{categoryName: "たんす"},{categoryName: "その他"}])
baby_kids_13 = baby_kids.children.create(categoryName: "おもちゃ")
baby_kids_13.children.create([{categoryName: "おふろのおもちゃ"},{categoryName: "がらがら"},{categoryName: "オルゴール"},{categoryName: "ベビージム"},{categoryName: "手押し車/カタカタ"},{categoryName: "知育玩具"},{categoryName: "その他"}])
baby_kids_14 = baby_kids.children.create(categoryName: "行事/記念品")
baby_kids_14.children.create([{categoryName: "お宮参り用品"},{categoryName: "お食い初め用品"},{categoryName: "アルバム"},{categoryName: "手形/足形"},{categoryName: "その他"}])
baby_kids_15 = baby_kids.children.create(categoryName: "その他")
baby_kids_15.children.create([{categoryName: "母子手帳用品"},{categoryName: "その他"}])

# インテリア・住まい・小物
interior_residence_accessory = Category.create(categoryName: "インテリア・住まい・小物")
interior_residence_accessory_1 = interior_residence_accessory.children.create(categoryName: "キッチン/食器")
interior_residence_accessory_1.children.create([{categoryName: "食器"},{categoryName: "調理器具"},{categoryName: "収納/キッチン雑貨"},{categoryName: "弁当用品"},{categoryName: "カトラリー(スプーン等)"},{categoryName: "テーブル用品"},{categoryName: "容器"},{categoryName: "エプロン"},{categoryName: "アルコールグッズ"},{categoryName: "浄水機"},{categoryName: "その他"}])
interior_residence_accessory_2 = interior_residence_accessory.children.create(categoryName: "ベッド/マットレス")
interior_residence_accessory_2.children.create([{categoryName: "セミシングルベッド"},{categoryName: "シングルベッド"},{categoryName: "セミダブルベッド"},{categoryName: "ダブルベッド"},{categoryName: "ワイドダブルベッド"},{categoryName: "クイーンベッド"},{categoryName: "キングベッド"},{categoryName: "脚付きマットレスベッド"},{categoryName: "マットレス"},{categoryName: "すのこベッド"},{categoryName: "ロフトベッド/システムベッド"},{categoryName: "簡易ベッド/折りたたみベッド"},{categoryName: "収納付き"},{categoryName: "その他"}])
interior_residence_accessory_3 = interior_residence_accessory.children.create(categoryName: "ソファ/ソファベッド")
interior_residence_accessory_3.children.create([{categoryName: "ソファセット"},{categoryName: "シングルソファ"},{categoryName: "ラブソファ"},{categoryName: "トリプルソファ"},{categoryName: "オットマン"},{categoryName: "コーナーソファ"},{categoryName: "ビーズソファ/クッションソファ"},{categoryName: "ローソファ/フロアソファ"},{categoryName: "ソファベッド"},{categoryName: "応接セット"},{categoryName: "ソファカバー"},{categoryName: "リクライニングソファ"},{categoryName: "その他"}])
interior_residence_accessory_4 = interior_residence_accessory.children.create(categoryName: "椅子/チェア")
interior_residence_accessory_4.children.create([{categoryName: "一般"},{categoryName: "スツール"},{categoryName: "ダイニングチェア"},{categoryName: "ハイバックチェア"},{categoryName: "ロッキングチェア"},{categoryName: "座椅子"},{categoryName: "折り畳みイス"},{categoryName: "デスクチェア"},{categoryName: "その他"}])
interior_residence_accessory_5 = interior_residence_accessory.children.create(categoryName: "机/テーブル")
interior_residence_accessory_5.children.create([{categoryName: "こたつ"},{categoryName: "カウンターテーブル"},{categoryName: "サイドテーブル"},{categoryName: "センターテーブル"},{categoryName: "ダイニングテーブル"},{categoryName: "座卓/ちゃぶ台"},{categoryName: "アウトドア用"},{categoryName: "パソコン用"},{categoryName: "事務机/学習机"},{categoryName: "その他"}])
interior_residence_accessory_6 = interior_residence_accessory.children.create(categoryName: "収納家具")
interior_residence_accessory_6.children.create([{categoryName: "リビング収納"},{categoryName: "キッチン収納"},{categoryName: "玄関/屋外収納"},{categoryName: "バス/トイレ収納"},{categoryName: "本収納"},{categoryName: "本/CD/DVD収納"},{categoryName: "洋服タンス/押入れ収納"},{categoryName: "電話台/ファックス台"},{categoryName: "ドレッサー/鏡台"},{categoryName: "棚/ラック"},{categoryName: "ケース/ボックス"},{categoryName: "その他"}])
interior_residence_accessory_7 = interior_residence_accessory.children.create(categoryName: "ラグ/カーペット/マット")
interior_residence_accessory_7.children.create([{categoryName: "ラグ"},{categoryName: "カーペット"},{categoryName: "ホットカーペット"},{categoryName: "玄関/キッチンマット"},{categoryName: "トイレ/バスマット"},{categoryName: "その他"}])
interior_residence_accessory_8 = interior_residence_accessory.children.create(categoryName: "カーテン/ブラインド")
interior_residence_accessory_8.children.create([{categoryName: "カーテン"},{categoryName: "ブラインド"},{categoryName: "ロールスクリーン"},{categoryName: "のれん"},{categoryName: "その他"}])
interior_residence_accessory_9 = interior_residence_accessory.children.create(categoryName: "ライト/照明")
interior_residence_accessory_9.children.create([{categoryName: "蛍光灯/電球"},{categoryName: "天井照明"},{categoryName: "フロアスタンド"},{categoryName: "その他"}])
interior_residence_accessory_10 = interior_residence_accessory.children.create(categoryName: "寝具")
interior_residence_accessory_10.children.create([{categoryName: "布団/毛布"},{categoryName: "枕"},{categoryName: "シーツ/カバー"},{categoryName: "その他"}])
interior_residence_accessory_11 = interior_residence_accessory.children.create(categoryName: "インテリア小物")
interior_residence_accessory_11.children.create([{categoryName: "ごみ箱"},{categoryName: "ウェルカムボード"},{categoryName: "オルゴール"},{categoryName: "クッション"},{categoryName: "クッションカバー"},{categoryName: "スリッパラック"},{categoryName: "ティッシュボックス"},{categoryName: "バスケット/かご"},{categoryName: "フォトフレーム"},{categoryName: "マガジンラック"},{categoryName: "モビール"},{categoryName: "モビール"},{categoryName: "花瓶"},{categoryName: "灰皿"},{categoryName: "傘立て"},{categoryName: "小物入れ"},{categoryName: "置時計"},{categoryName: "掛時計/柱時計"},{categoryName: "鏡(立て掛け式)"},{categoryName: "鏡(壁掛け式)"},{categoryName: "置物"},{categoryName: "風鈴"},{categoryName: "植物/観葉植物"},{categoryName: "その他"}])
interior_residence_accessory_12 = interior_residence_accessory.children.create(categoryName: "季節/年中行事")
interior_residence_accessory_12.children.create([{categoryName: "正月"},{categoryName: "成人式"},{categoryName: "バレンタインデー"},{categoryName: "ひな祭り"},{categoryName: "子どもの日"},{categoryName: "母の日"},{categoryName: "父の日"},{categoryName: "父の日"},{categoryName: "サマーギフト/お中元"},{categoryName: "夏/夏休み"},{categoryName: "ハロウィン"},{categoryName: "敬老の日"},{categoryName: "七五三"},{categoryName: "お歳暮"},{categoryName: "クリスマス"},{categoryName: "冬一般"},{categoryName: "その他"}])
interior_residence_accessory_13 = interior_residence_accessory.children.create(categoryName: "その他")
interior_residence_accessory_13.children.create([{categoryName: "すべて"}])

# 本・音楽・ゲーム
book_music_game = Category.create(categoryName: "本・音楽・ゲーム")
book_music_game_1 = book_music_game.children.create(categoryName: "本")
book_music_game_1.children.create([{categoryName: "文学/小説"},{categoryName: "人文/社会"},{categoryName: "ノンフィクション/教養"},{categoryName: "地図/旅行ガイド"},{categoryName: "ビジネス/経済"},{categoryName: "ビジネス/経済"},{categoryName: "健康/医学"},{categoryName: "コンピュータ/IT"},{categoryName: "趣味/スポーツ/実用"},{categoryName: "住まい/暮らし/子育て"},{categoryName: "アート/エンタメ"},{categoryName: "洋書"},{categoryName: "絵本"},{categoryName: "参考書"},{categoryName: "その他"}])
book_music_game_2 = book_music_game.children.create(categoryName: "漫画")
book_music_game_2.children.create([{categoryName: "全巻セット"},{categoryName: "少年漫画"},{categoryName: "少女漫画"},{categoryName: "青年漫画"},{categoryName: "女性漫画"},{categoryName: "同人誌"},{categoryName: "その他"}])
book_music_game_3 = book_music_game.children.create(categoryName: "雑誌")
book_music_game_3.children.create([{categoryName: "アート/エンタメ/ホビー"},{categoryName: "ファッション"},{categoryName: "ニュース/総合"},{categoryName: "趣味/スポーツ"},{categoryName: "その他"}])
book_music_game_4 = book_music_game.children.create(categoryName: "CD")
book_music_game_4.children.create([{categoryName: "邦楽"},{categoryName: "洋楽"},{categoryName: "アニメ"},{categoryName: "クラシック"},{categoryName: "K-POP/アジア"},{categoryName: "キッズ/ファミリー"},{categoryName: "その他"}])
book_music_game_5 = book_music_game.children.create(categoryName: "DVD/ブルーレイ")
book_music_game_5.children.create([{categoryName: "外国映画"},{categoryName: "日本映画"},{categoryName: "アニメ"},{categoryName: "TVドラマ"},{categoryName: "ミュージック"},{categoryName: "お笑い/バラエティ"},{categoryName: "スポーツ/フィットネス"},{categoryName: "キッズ/ファミリー"},{categoryName: "その他"}])
book_music_game_6 = book_music_game.children.create(categoryName: "レコード")
book_music_game_6.children.create([{categoryName: "邦楽"},{categoryName: "洋楽"},{categoryName: "その他"}])
book_music_game_7 = book_music_game.children.create(categoryName: "テレビゲーム")
book_music_game_7.children.create([{categoryName: "家庭用ゲーム本体"},{categoryName: "家庭用ゲームソフト"},{categoryName: "携帯用ゲーム本体"},{categoryName: "携帯用ゲームソフト"},{categoryName: "PCゲーム"},{categoryName: "その他"}])

# おもちゃ・ホビー・グッズ
toy_hobby_goods = Category.create(categoryName: "おもちゃ・ホビー・グッズ")
toy_hobby_goods_1 = toy_hobby_goods.children.create(categoryName: "おもちゃ")
toy_hobby_goods_1.children.create([{categoryName: "キャラクターグッズ"},{categoryName: "ぬいぐるみ"},{categoryName: "小物/アクセサリー"},{categoryName: "模型/プラモデル"},{categoryName: "ミニカー"},{categoryName: "トイラジコン"},{categoryName: "プラモデル"},{categoryName: "ホビーラジコン"},{categoryName: "鉄道模型"},{categoryName: "その他"}])
toy_hobby_goods_2 = toy_hobby_goods.children.create(categoryName: "タレントグッズ")
toy_hobby_goods_2.children.create([{categoryName: "アイドル"},{categoryName: "ミュージシャン"},{categoryName: "タレント/お笑い芸人"},{categoryName: "スポーツ選手"},{categoryName: "その他"}])
toy_hobby_goods_3 = toy_hobby_goods.children.create(categoryName: "コミック/アニメグッズ")
toy_hobby_goods_3.children.create([{categoryName: "ストラップ"},{categoryName: "キーホルダー"},{categoryName: "バッジ"},{categoryName: "カード"},{categoryName: "クリアファイル"},{categoryName: "ポスター"},{categoryName: "タオル"},{categoryName: "その他"}])
toy_hobby_goods_4 = toy_hobby_goods.children.create(categoryName: "トレーディングカード")
toy_hobby_goods_4.children.create([{categoryName: "遊戯王"},{categoryName: "マジック：ザ・ギャザリング"},{categoryName: "ポケモンカードゲーム"},{categoryName: "デュエルマスターズ"},{categoryName: "バトルスピリッツ"},{categoryName: "プリパラ"},{categoryName: "アイカツ"},{categoryName: "カードファイト!! ヴァンガード"},{categoryName: "ヴァイスシュヴァルツ"},{categoryName: "プロ野球オーナーズリーグ"},{categoryName: "ベースボールヒーローズ"},{categoryName: "ドラゴンボール"},{categoryName: "スリーブ"},{categoryName: "その他"}])
toy_hobby_goods_5 = toy_hobby_goods.children.create(categoryName: "フィギュア")
toy_hobby_goods_5.children.create([{categoryName: "コミック/アニメ"},{categoryName: "特撮"},{categoryName: "ゲームキャラクター"},{categoryName: "SF/ファンタジー/ホラー"},{categoryName: "アメコミ"},{categoryName: "スポーツ"},{categoryName: "ミリタリー"},{categoryName: "その他"}])
toy_hobby_goods_6 = toy_hobby_goods.children.create(categoryName: "楽器/器材")
toy_hobby_goods_6.children.create([{categoryName: "エレキギター"},{categoryName: "アコースティックギター"},{categoryName: "ベース"},{categoryName: "エフェクター"},{categoryName: "アンプ"},{categoryName: "弦楽器"},{categoryName: "管楽器"},{categoryName: "鍵盤楽器"},{categoryName: "打楽器"},{categoryName: "和楽器"},{categoryName: "楽譜/スコア"},{categoryName: "レコーディング/PA機器"},{categoryName: "DJ機器"},{categoryName: "DTM/DAW"},{categoryName: "その他"}])
toy_hobby_goods_7 = toy_hobby_goods.children.create(categoryName: "コレクション")
toy_hobby_goods_7.children.create([{categoryName: "武具"},{categoryName: "使用済切手/官製はがき"},{categoryName: "旧貨幣/金貨/銀貨/記念硬貨"},{categoryName: "印刷物"},{categoryName: "ノベルティグッズ"},{categoryName: "その他"}])
toy_hobby_goods_8 = toy_hobby_goods.children.create(categoryName: "ミリタリー")
toy_hobby_goods_8.children.create([{categoryName: "トイガン"},{categoryName: "個人装備"},{categoryName: "その他"}])
toy_hobby_goods_9 = toy_hobby_goods.children.create(categoryName: "美術品")
toy_hobby_goods_9.children.create([{categoryName: "陶芸"},{categoryName: "ガラス"},{categoryName: "漆芸"},{categoryName: "金属工芸"},{categoryName: "絵画/タペストリ"},{categoryName: "版画"},{categoryName: "彫刻/オブジェクト"},{categoryName: "書"},{categoryName: "写真"},{categoryName: "その他"}])
toy_hobby_goods_10 = toy_hobby_goods.children.create(categoryName: "アート用品")
toy_hobby_goods_10.children.create([{categoryName: "画材"},{categoryName: "額縁"},{categoryName: "その他"}])
toy_hobby_goods_11 = toy_hobby_goods.children.create(categoryName: "その他")
toy_hobby_goods_11.children.create([{categoryName: "トランプ/UNO"},{categoryName: "カルタ/百人一首"},{categoryName: "ダーツ"},{categoryName: "ビリヤード"},{categoryName: "麻雀"},{categoryName: "パズル/ジグソーパズル"},{categoryName: "囲碁/将棋"},{categoryName: "オセロ/チェス"},{categoryName: "人生ゲーム"},{categoryName: "野球/サッカーゲーム"},{categoryName: "スポーツ"},{categoryName: "三輪車/乗り物"},{categoryName: "ヨーヨー"},{categoryName: "模型製作用品"},{categoryName: "鉄道"},{categoryName: "航空機"},{categoryName: "アマチュア無線"},{categoryName: "パチンコ/パチスロ"},{categoryName: "その他"}])

# コスメ・香水・美容
cosme_perfume_beauty = Category.create(categoryName: "コスメ・香水・美容")
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(categoryName: "ベースメイク")
cosme_perfume_beauty_1.children.create([{categoryName: "ファンデーション"},{categoryName: "化粧下地"},{categoryName: "コントロールカラー"},{categoryName: "BBクリーム"},{categoryName: "CCクリーム"},{categoryName: "コンシーラー"},{categoryName: "フェイスパウダー"},{categoryName: "トライアルセット/サンプル"},{categoryName: "その他"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(categoryName: "メイクアップ")
cosme_perfume_beauty_2.children.create([{categoryName: "アイシャドウ"},{categoryName: "口紅"},{categoryName: "リップグロス"},{categoryName: "リップライナー"},{categoryName: "チーク"},{categoryName: "フェイスカラー"},{categoryName: "マスカラ"},{categoryName: "アイライナー"},{categoryName: "つけまつげ"},{categoryName: "アイブロウペンシル"},{categoryName: "パウダーアイブロウ"},{categoryName: "眉マスカラ"},{categoryName: "トライアルセット/サンプル"},{categoryName: "メイク道具/化粧小物"},{categoryName: "美顔用品/美顔ローラー"},{categoryName: "その他"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(categoryName: "ネイルケア")
cosme_perfume_beauty_3.children.create([{categoryName: "ネイルカラー"},{categoryName: "カラージェル"},{categoryName: "ネイルベースコート/トップコート"},{categoryName: "ネイルアート用品"},{categoryName: "ネイルパーツ"},{categoryName: "ネイルチップ/付け爪"},{categoryName: "手入れ用具"},{categoryName: "除光液"},{categoryName: "その他"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(categoryName: "香水")
cosme_perfume_beauty_4.children.create([{categoryName: "香水(女性用)"},{categoryName: "香水(男性用)"},{categoryName: "ユニセックス"},{categoryName: "ボディミスト"},{categoryName: "その他"}])
cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(categoryName: "スキンケア/基礎化粧品")
cosme_perfume_beauty_5.children.create([{categoryName: "化粧水/ローション"},{categoryName: "乳液/ミルク"},{categoryName: "美容液"},{categoryName: "フェイスクリーム"},{categoryName: "洗顔料"},{categoryName: "クレンジング/メイク落とし"},{categoryName: "パック/フェイスマスク"},{categoryName: "ジェル/ゲル"},{categoryName: "ブースター/導入液"},{categoryName: "アイケア"},{categoryName: "リップケア"},{categoryName: "トライアルセット/サンプル"},{categoryName: "洗顔グッズ"},{categoryName: "その他"}])
cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(categoryName: "ヘアケア")
cosme_perfume_beauty_6.children.create([{categoryName: "シャンプー"},{categoryName: "トリートメント"},{categoryName: "コンディショナー"},{categoryName: "リンス"},{categoryName: "スタイリング剤"},{categoryName: "カラーリング剤"},{categoryName: "ブラシ"},{categoryName: "その他"}])
cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(categoryName: "ボディケア")
cosme_perfume_beauty_7.children.create([{categoryName: "オイル/クリーム"},{categoryName: "ハンドクリーム"},{categoryName: "ローション"},{categoryName: "日焼け止め/サンオイル"},{categoryName: "ボディソープ"},{categoryName: "入浴剤"},{categoryName: "制汗/デオドラント"},{categoryName: "フットケア"},{categoryName: "その他"}])
cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(categoryName: "オーラルケア")
cosme_perfume_beauty_8.children.create([{categoryName: "口臭防止/エチケット用品"},{categoryName: "歯ブラシ"},{categoryName: "その他"}])
cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(categoryName: "リラクゼーション")
cosme_perfume_beauty_9.children.create([{categoryName: "エッセンシャルオイル"},{categoryName: "芳香器"},{categoryName: "お香/香炉"},{categoryName: "キャンドル"},{categoryName: "リラクゼーショングッズ"},{categoryName: "その他"}])
cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(categoryName: "ダイエット")
cosme_perfume_beauty_10.children.create([{categoryName: "ダイエット食品"},{categoryName: "エクササイズ用品"},{categoryName: "体重計"},{categoryName: "体脂肪計"},{categoryName: "その他"}])
cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(categoryName: "その他")
cosme_perfume_beauty_11.children.create([{categoryName: "健康用品"},{categoryName: "看護/介護用品"},{categoryName: "救急/衛生用品"},{categoryName: "その他"}])

# 家電・スマホ・カメラ
appliance_smartphone_camera = Category.create(categoryName: "家電・スマホ・カメラ")
appliance_smartphone_camera_1 = appliance_smartphone_camera.children.create(categoryName: "スマートフォン/携帯電話")
appliance_smartphone_camera_1.children.create([{categoryName: "スマートフォン本体"},{categoryName: "バッテリー/充電器"},{categoryName: "携帯電話本体"},{categoryName: "PHS本体"},{categoryName: "その他"}])
appliance_smartphone_camera_2 = appliance_smartphone_camera.children.create(categoryName: "スマホアクセサリー")
appliance_smartphone_camera_2.children.create([{categoryName: "Android用ケース"},{categoryName: "iPhone用ケース"},{categoryName: "カバー"},{categoryName: "イヤホンジャック"},{categoryName: "ストラップ"},{categoryName: "フィルム"},{categoryName: "自撮り棒"},{categoryName: "その他"}])
appliance_smartphone_camera_3 = appliance_smartphone_camera.children.create(categoryName: "PC/タブレット")
appliance_smartphone_camera_3.children.create([{categoryName: "タブレット"},{categoryName: "ノートPC"},{categoryName: "デスクトップ型PC"},{categoryName: "ディスプレイ"},{categoryName: "電子ブックリーダー"},{categoryName: "PC周辺機器"},{categoryName: "PCパーツ"},{categoryName: "その他"}])
appliance_smartphone_camera_4 = appliance_smartphone_camera.children.create(categoryName: "カメラ")
appliance_smartphone_camera_4.children.create([{categoryName: "デジタルカメラ"},{categoryName: "ビデオカメラ"},{categoryName: "レンズ(単焦点)"},{categoryName: "レンズ(ズーム)"},{categoryName: "フィルムカメラ"},{categoryName: "防犯カメラ"},{categoryName: "その他"}])
appliance_smartphone_camera_5 = appliance_smartphone_camera.children.create(categoryName: "テレビ/映像機器")
appliance_smartphone_camera_5.children.create([{categoryName: "テレビ"},{categoryName: "プロジェクター"},{categoryName: "ブルーレイレコーダー"},{categoryName: "DVDレコーダー"},{categoryName: "ブルーレイプレーヤー"},{categoryName: "DVDプレーヤー"},{categoryName: "映像用ケーブル"},{categoryName: "その他"}])
appliance_smartphone_camera_6 = appliance_smartphone_camera.children.create(categoryName: "オーディオ機器")
appliance_smartphone_camera_6.children.create([{categoryName: "ポータブルプレーヤー"},{categoryName: "イヤフォン"},{categoryName: "ヘッドフォン"},{categoryName: "アンプ"},{categoryName: "スピーカー"},{categoryName: "ケーブル/シールド"},{categoryName: "ラジオ"},{categoryName: "その他"}])
appliance_smartphone_camera_7 = appliance_smartphone_camera.children.create(categoryName: "美容/健康")
appliance_smartphone_camera_7.children.create([{categoryName: "ヘアドライヤー"},{categoryName: "ヘアアイロン"},{categoryName: "美容機器"},{categoryName: "電気シェーバー"},{categoryName: "電動歯ブラシ"},{categoryName: "その他"}])
appliance_smartphone_camera_8 = appliance_smartphone_camera.children.create(categoryName: "冷暖房/空調")
appliance_smartphone_camera_8.children.create([{categoryName: "エアコン"},{categoryName: "空気清浄器"},{categoryName: "加湿器"},{categoryName: "扇風機"},{categoryName: "除湿機"},{categoryName: "ファンヒーター"},{categoryName: "電気ヒーター"},{categoryName: "オイルヒーター"},{categoryName: "ストーブ"},{categoryName: "ホットカーペット"},{categoryName: "こたつ"},{categoryName: "電気毛布"},{categoryName: "その他"}])
appliance_smartphone_camera_9 = appliance_smartphone_camera.children.create(categoryName: "生活家電")
appliance_smartphone_camera_9.children.create([{categoryName: "冷蔵庫"},{categoryName: "洗濯機"},{categoryName: "炊飯器"},{categoryName: "電子レンジ/オーブン"},{categoryName: "調理機器"},{categoryName: "アイロン"},{categoryName: "掃除機"},{categoryName: "エスプレッソマシン"},{categoryName: "コーヒーメーカー"},{categoryName: "衣類乾燥機"},{categoryName: "その他"}])
appliance_smartphone_camera_10 = appliance_smartphone_camera.children.create(categoryName: "その他")
appliance_smartphone_camera_10.children.create([{categoryName: "その他"}])

# スポーツ・レジャー
sport_leisure = Category.create(categoryName: "スポーツ・レジャー")
sport_leisure_1 = sport_leisure.children.create(categoryName: "ゴルフ")
sport_leisure_1.children.create([{categoryName: "クラブ"},{categoryName: "ウエア(男性用)"},{categoryName: "ウエア(女性用)"},{categoryName: "バッグ"},{categoryName: "シューズ(男性用)"},{categoryName: "シューズ(女性用)"},{categoryName: "アクセサリー"},{categoryName: "その他"}])
sport_leisure_2 = sport_leisure.children.create(categoryName: "フィッシング")
sport_leisure_2.children.create([{categoryName: "ロッド"},{categoryName: "リール"},{categoryName: "ルアー用品"},{categoryName: "ウエア"},{categoryName: "釣り糸/ライン"},{categoryName: "その他"}])
sport_leisure_3 = sport_leisure.children.create(categoryName: "自転車")
sport_leisure_3.children.create([{categoryName: "自転車本体"},{categoryName: "ウエア"},{categoryName: "パーツ"},{categoryName: "アクセサリー"},{categoryName: "バッグ"},{categoryName: "工具/メンテナンス"},{categoryName: "その他"}])
sport_leisure_4 = sport_leisure.children.create(categoryName: "トレーニング/エクササイズ")
sport_leisure_4.children.create([{categoryName: "ランニング"},{categoryName: "ウォーキング"},{categoryName: "ヨガ"},{categoryName: "トレーニング用品"},{categoryName: "その他"}])
sport_leisure_5 = sport_leisure.children.create(categoryName: "野球")
sport_leisure_5.children.create([{categoryName: "ウェア"},{categoryName: "シューズ"},{categoryName: "グローブ"},{categoryName: "バット"},{categoryName: "アクセサリー"},{categoryName: "防具"},{categoryName: "練習機器"},{categoryName: "記念グッズ"},{categoryName: "応援グッズ"},{categoryName: "その他"}])
sport_leisure_6 = sport_leisure.children.create(categoryName: "サッカー/フットサル")
sport_leisure_6.children.create([{categoryName: "ウェア"},{categoryName: "シューズ"},{categoryName: "ボール"},{categoryName: "アクセサリー"},{categoryName: "記念グッズ"},{categoryName: "応援グッズ"},{categoryName: "その他"}])
sport_leisure_7 = sport_leisure.children.create(categoryName: "テニス")
sport_leisure_7.children.create([{categoryName: "ラケット(硬式用)"},{categoryName: "ラケット(軟式用)"},{categoryName: "ウェア"},{categoryName: "シューズ"},{categoryName: "ボール"},{categoryName: "アクセサリー"},{categoryName: "記念グッズ"},{categoryName: "応援グッズ"},{categoryName: "その他"}])
sport_leisure_8 = sport_leisure.children.create(categoryName: "スノーボード")
sport_leisure_8.children.create([{categoryName: "ボード"},{categoryName: "バインディング"},{categoryName: "ブーツ(男性用)"},{categoryName: "ブーツ(女性用)"},{categoryName: "ブーツ(子ども用)"},{categoryName: "ウエア/装備(男性用)"},{categoryName: "ウエア/装備(女性用)"},{categoryName: "ウエア/装備(子ども用)"},{categoryName: "アクセサリー"},{categoryName: "バッグ"},{categoryName: "その他"}])
sport_leisure_9 = sport_leisure.children.create(categoryName: "スキー")
sport_leisure_9.children.create([{categoryName: "板"},{categoryName: "ブーツ(男性用)"},{categoryName: "ブーツ(女性用)"},{categoryName: "ブーツ(子ども用)"},{categoryName: "ビンディング"},{categoryName: "ウエア(男性用)"},{categoryName: "ウエア(女性用)"},{categoryName: "ウエア(子ども用)"},{categoryName: "ストック"},{categoryName: "その他"}])
sport_leisure_10 = sport_leisure.children.create(categoryName: "その他スポーツ")
sport_leisure_10.children.create([{categoryName: "ダンス/バレエ"},{categoryName: "サーフィン"},{categoryName: "バスケットボール"},{categoryName: "バドミントン"},{categoryName: "バレーボール"},{categoryName: "スケートボード"},{categoryName: "陸上競技"},{categoryName: "ラグビー"},{categoryName: "アメリカンフットボール"},{categoryName: "ボクシング"},{categoryName: "ボウリング"},{categoryName: "その他"}])
sport_leisure_11 = sport_leisure.children.create(categoryName: "アウトドア")
sport_leisure_11.children.create([{categoryName: "テント/タープ"},{categoryName: "ライト/ランタン"},{categoryName: "寝袋/寝具"},{categoryName: "テーブル/チェア"},{categoryName: "ストーブ/コンロ"},{categoryName: "調理器具"},{categoryName: "食器"},{categoryName: "登山用品"},{categoryName: "その他"}])
sport_leisure_12 = sport_leisure.children.create(categoryName: "その他")
sport_leisure_12.children.create([{categoryName: "旅行用品"},{categoryName: "その他"}])

# ハンドメイド
handmade = Category.create(categoryName: "ハンドメイド")
handmade_1 = handmade.children.create(categoryName: "アクセサリー(女性用)")
handmade_1.children.create([{categoryName: "ピアス"},{categoryName: "イヤリング"},{categoryName: "ネックレス"},{categoryName: "ブレスレット"},{categoryName: "リング"},{categoryName: "チャーム"},{categoryName: "ヘアゴム"},{categoryName: "アンクレット"},{categoryName: "その他"}])
handmade_2 = handmade.children.create(categoryName: "ファッション/小物")
handmade_2.children.create([{categoryName: "バッグ(女性用)"},{categoryName: "バッグ(男性用)"},{categoryName: "財布(女性用)"},{categoryName: "財布(男性用)"},{categoryName: "ファッション雑貨"},{categoryName: "その他"}])
handmade_3 = handmade.children.create(categoryName: "アクセサリー/時計")
handmade_3.children.create([{categoryName: "アクセサリー(男性用)"},{categoryName: "時計(女性用)"},{categoryName: "時計(男性用)"},{categoryName: "その他"}])
handmade_4 = handmade.children.create(categoryName: "日用品/インテリア")
handmade_4.children.create([{categoryName: "キッチン用品"},{categoryName: "家具"},{categoryName: "文房具"},{categoryName: "アート/写真"},{categoryName: "アロマ/キャンドル"},{categoryName: "フラワー/ガーデン"},{categoryName: "その他"}])
handmade_5 = handmade.children.create(categoryName: "趣味/おもちゃ")
handmade_5.children.create([{categoryName: "クラフト/布製品"},{categoryName: "おもちゃ/人形"},{categoryName: "その他"}])
handmade_6 = handmade.children.create(categoryName: "キッズ/ベビー")
handmade_6.children.create([{categoryName: "ファッション雑貨"},{categoryName: "スタイ/よだれかけ"},{categoryName: "外出用品"},{categoryName: "ネームタグ"},{categoryName: "その他"}])
handmade_7 = handmade.children.create(categoryName: "素材/材料")
handmade_7.children.create([{categoryName: "各種パーツ"},{categoryName: "生地/糸"},{categoryName: "型紙/パターン"},{categoryName: "その他"}])
handmade_8 = handmade.children.create(categoryName: "二次創作物")
handmade_8.children.create([{categoryName: "Ingress"},{categoryName: "クリエイターズ宇宙兄弟"},{categoryName: "その他"},{categoryName: "チケット"},{categoryName: "すべて"}])
handmade_9 = handmade.children.create(categoryName: "その他")
handmade_9.children.create([{categoryName: "すべて"}])

# チケット
ticket = Category.create(categoryName: "チケット")
ticket_1 = ticket.children.create(categoryName: "音楽")
ticket_1.children.create([{categoryName: "男性アイドル"},{categoryName: "女性アイドル"},{categoryName: "韓流"},{categoryName: "国内アーティスト"},{categoryName: "海外アーティスト"},{categoryName: "音楽フェス"},{categoryName: "声優/アニメ"},{categoryName: "その他"}])
ticket_2 = ticket.children.create(categoryName: "スポーツ")
ticket_2.children.create([{categoryName: "サッカー"},{categoryName: "野球"},{categoryName: "テニス"},{categoryName: "格闘技/プロレス"},{categoryName: "相撲/武道"},{categoryName: "ゴルフ"},{categoryName: "バレーボール"},{categoryName: "バスケットボール"},{categoryName: "モータースポーツ"},{categoryName: "ウィンタースポーツ"},{categoryName: "その他"}])
ticket_3 = ticket.children.create(categoryName: "演劇/芸能")
ticket_3.children.create([{categoryName: "ミュージカル"},{categoryName: "演劇"},{categoryName: "伝統芸能"},{categoryName: "落語"},{categoryName: "お笑い"},{categoryName: "オペラ"},{categoryName: "サーカス"},{categoryName: "バレエ"},{categoryName: "その他"}])
ticket_4 = ticket.children.create(categoryName: "イベント")
ticket_4.children.create([{categoryName: "声優/アニメ"},{categoryName: "キッズ/ファミリー"},{categoryName: "トークショー/講演会"},{categoryName: "その他"}])
ticket_5 = ticket.children.create(categoryName: "映画")
ticket_5.children.create([{categoryName: "邦画"},{categoryName: "洋画"},{categoryName: "その他"}])
ticket_6 = ticket.children.create(categoryName: "施設利用券")
ticket_6.children.create([{categoryName: "遊園地/テーマパーク"},{categoryName: "美術館/博物館"},{categoryName: "スキー場"},{categoryName: "ゴルフ場"},{categoryName: "フィットネスクラブ"},{categoryName: "プール"},{categoryName: "ボウリング場"},{categoryName: "水族館"},{categoryName: "動物園"},{categoryName: "その他"}])
ticket_7 = ticket.children.create(categoryName: "優待券/割引券")
ticket_7.children.create([{categoryName: "ショッピング"},{categoryName: "レストラン/食事券"},{categoryName: "フード/ドリンク券"},{categoryName: "宿泊券"},{categoryName: "その他"}])
ticket_8 = ticket.children.create(categoryName: "その他")
ticket_8.children.create([{categoryName: "すべて"}])


# 自動車・オートバイ
car_motorcycle = Category.create(categoryName: "自動車・オートバイ")
car_motorcycle_1 = car_motorcycle.children.create(categoryName: "自動車本体")
car_motorcycle_1.children.create([{categoryName: "国内自動車本体"},{categoryName: "外国自動車本体"}])
car_motorcycle_2 = car_motorcycle.children.create(categoryName: "自動車タイヤ/ホイール")
car_motorcycle_2.children.create([{categoryName: "タイヤ/ホイールセット"},{categoryName: "タイヤ"},{categoryName: "ホイール"},{categoryName: "その他"}])
car_motorcycle_3 = car_motorcycle.children.create(categoryName: "自動車パーツ")
car_motorcycle_3.children.create([{categoryName: "サスペンション"},{categoryName: "ブレーキ"},{categoryName: "外装、エアロパーツ"},{categoryName: "ライト"},{categoryName: "内装品、シート"},{categoryName: "ステアリング"},{categoryName: "マフラー・排気系"},{categoryName: "エンジン、過給器、冷却装置"},{categoryName: "クラッチ、ミッション、駆動系"},{categoryName: "電装品"},{categoryName: "補強パーツ"},{categoryName: "汎用パーツ"},{categoryName: "外国自動車用パーツ"},{categoryName: "その他"}])
car_motorcycle_4 = car_motorcycle.children.create(categoryName: "自動車アクセサリー")
car_motorcycle_4.children.create([{categoryName: "車内アクセサリー"},{categoryName: "カーナビ"},{categoryName: "カーオーディオ"},{categoryName: "車外アクセサリー"},{categoryName: "メンテナンス用品"},{categoryName: "チャイルドシート"},{categoryName: "ドライブレコーダー"},{categoryName: "レーダー探知機"},{categoryName: "カタログ/マニュアル"},{categoryName: "セキュリティ"},{categoryName: "ETC"},{categoryName: "その他"}])
car_motorcycle_5 = car_motorcycle.children.create(categoryName: "オートバイ車体")
car_motorcycle_5.children.create([{categoryName: "すべて"}])
car_motorcycle_6 = car_motorcycle.children.create(categoryName: "オートバイパーツ")
car_motorcycle_6.children.create([{categoryName: "タイヤ"},{categoryName: "マフラー"},{categoryName: "エンジン、冷却装置"},{categoryName: "カウル、フェンダー、外装"},{categoryName: "サスペンション"},{categoryName: "ホイール"},{categoryName: "シート"},{categoryName: "ブレーキ"},{categoryName: "タンク"},{categoryName: "ライト、ウィンカー"},{categoryName: "チェーン、スプロケット、駆動系"},{categoryName: "メーター"},{categoryName: "電装系"},{categoryName: "ミラー"},{categoryName: "外国オートバイ用パーツ"},{categoryName: "その他"}])
car_motorcycle_7 = car_motorcycle.children.create(categoryName: "オートバイアクセサリー")
car_motorcycle_7.children.create([{categoryName: "ヘルメット/シールド"},{categoryName: "バイクウエア/装備"},{categoryName: "アクセサリー"},{categoryName: "メンテナンス"},{categoryName: "カタログ/マニュアル"},{categoryName: "その他"}])

# その他
others = Category.create(categoryName: "その他")
others_1 = others.children.create(categoryName: "まとめ売り")
others_1.children.create([{categoryName: "すべて"}])
others_2 = others.children.create(categoryName: "ペット用品")
others_2.children.create([{categoryName: "ペットフード"},{categoryName: "犬用品"},{categoryName: "猫用品"},{categoryName: "魚用品/水草"},{categoryName: "小動物用品"},{categoryName: "爬虫類/両生類用品"},{categoryName: "かご/おり"},{categoryName: "鳥用品"},{categoryName: "虫類用品"},{categoryName: "その他"}])
others_3 = others.children.create(categoryName: "食品")
others_3.children.create([{categoryName: "菓子"},{categoryName: "米"},{categoryName: "野菜"},{categoryName: "果物"},{categoryName: "調味料"},{categoryName: "魚介類(加工食品)"},{categoryName: "肉類(加工食品)"},{categoryName: "その他 加工食品"},{categoryName: "その他"}])
others_4 = others.children.create(categoryName: "飲料/酒")
others_4.children.create([{categoryName: "コーヒー"},{categoryName: "ソフトドリンク"},{categoryName: "ミネラルウォーター"},{categoryName: "茶"},{categoryName: "ウイスキー"},{categoryName: "ワイン"},{categoryName: "ブランデー"},{categoryName: "焼酎"},{categoryName: "日本酒"},{categoryName: "ビール、発泡酒"},{categoryName: "その他"}])
others_5 = others.children.create(categoryName: "日用品/生活雑貨/旅行")
others_5.children.create([{categoryName: "タオル/バス用品"},{categoryName: "日用品/生活雑貨"},{categoryName: "洗剤/柔軟剤"},{categoryName: "旅行用品"},{categoryName: "防災関連グッズ"},{categoryName: "その他"}])
others_6 = others.children.create(categoryName: "アンティーク/コレクション")
others_6.children.create([{categoryName: "雑貨"},{categoryName: "工芸品"},{categoryName: "家具"},{categoryName: "印刷物"},{categoryName: "その他"}])
others_7 = others.children.create(categoryName: "文房具/事務用品")
others_7.children.create([{categoryName: "筆記具"},{categoryName: "ノート/メモ帳"},{categoryName: "テープ/マスキングテープ"},{categoryName: "カレンダー/スケジュール"},{categoryName: "アルバム/スクラップ"},{categoryName: "ファイル/バインダー"},{categoryName: "はさみ/カッター"},{categoryName: "カードホルダー/名刺管理"},{categoryName: "のり/ホッチキス"},{categoryName: "その他"}])
others_8 = others.children.create(categoryName: "事務/店舗用品")
others_8.children.create([{categoryName: "オフィス用品一般"},{categoryName: "オフィス家具"},{categoryName: "店舗用品"},{categoryName: "OA機器"},{categoryName: "ラッピング/包装"},{categoryName: "その他"}])
others_9 = others.children.create(categoryName: "その他")
others_9.children.create([{categoryName: "すべて"}])
